[package]
name = "sendme"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
bao = "0.12.1"
blake3 = "1.3.3"
bytes = "1.3.0"
clap = { version = "4", features = ["derive"] }
der = { version = "0.6.1", features = ["alloc", "derive"] }
ed25519-dalek = "1.0.1"
futures = "0.3.25"
hex = "0.4.3"
indicatif = { version = "0.17.2", features = ["tokio"] }
postcard = { version = "1.0.2", default-features = false, features = ["alloc", "use-std"] }
rand = "0.7"
rcgen = "0.10.0"
ring = "0.16.20"
rustls = { version = "0.20.8", default-features = false, features = ["dangerous_configuration"] }
s2n-quic = { version = "1.14.0", default-features = false, features = [ "provider-tls-rustls", "provider-address-token-default" ] }
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
tokio = { version = "1.24.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io-util", "io"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
unsigned-varint = { version = "0.7.1", features = ["futures"] }
webpki = "0.22.0"
x509-parser = "0.14.0"


[dev-dependencies]
testdir = "0.7.1"
