[package]
name = "sendme"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT/Apache-2.0"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
repository = "https://github.com/n0-computer/sendme"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.64"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bao = "0.12.1"
base64 = "0.21.0"
blake3 = "1.3.3"
bytes = "1"
clap = { version = "4", features = ["derive"], optional = true }
console = { version = "0.15.5", optional = true }
der = { version = "0.6", features = ["alloc", "derive"] }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
futures = "0.3.25"
indicatif = { version = "0.17", features = ["tokio"], optional = true }
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"] }
rand = "0.7"
rcgen = "0.10"
ring = "0.16.20"
rustls = { version = "0.20.8", default-features = false, features = ["dangerous_configuration"] }
s2n-quic = { version = "1.14.0", default-features = false, features = [ "provider-tls-rustls", "provider-address-token-default" ] }
serde = { version = "1", features = ["derive"] }
ssh-key = { version = "0.5.1", features = ["ed25519", "std", "rand_core"] }
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io-util", "io"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
webpki = "0.22"
x509-parser = "0.14"
zeroize = "1.5"

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"
rand = "0.7"
testdir = "0.7.1"

[features]
default = ["cli"]
cli = ["clap", "console", "indicatif"]

[[bin]]
name = "sendme"
required-features = ["cli"]
